# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(240, 40, 75, 24))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(70, 50, 75, 24))
        self.pushButton_2.setObjectName("pushButton_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(80, 140, 104, 71))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.radioButton = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(240, 120, 121, 20))
        self.radioButton.setObjectName("radioButton")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(240, 150, 121, 20))
        self.radioButton_2.setObjectName("radioButton_2")
        self.buttonGroup.addButton(self.radioButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(100, 210, 75, 24))
        self.pushButton_3.setObjectName("pushButton_3")
        self.subwindow_0 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.subwindow_0.setGeometry(QtCore.QRect(240, 210, 75, 24))
        self.subwindow_0.setObjectName("subwindow_0")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuSetBoardCoords = QtWidgets.QMenu(parent=self.menubar)
        self.menuSetBoardCoords.setObjectName("menuSetBoardCoords")
        self.menuabc123 = QtWidgets.QMenu(parent=self.menuSetBoardCoords)
        self.menuabc123.setObjectName("menuabc123")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionab = QtGui.QAction(parent=MainWindow)
        self.actionab.setObjectName("actionab")
        self.actionab_2 = QtGui.QAction(parent=MainWindow)
        self.actionab_2.setObjectName("actionab_2")
        self.actionhello = QtGui.QAction(parent=MainWindow)
        self.actionhello.setObjectName("actionhello")
        self.menuabc123.addSeparator()
        self.menuabc123.addAction(self.actionhello)
        self.menuSetBoardCoords.addSeparator()
        self.menuSetBoardCoords.addSeparator()
        self.menuSetBoardCoords.addSeparator()
        self.menuSetBoardCoords.addSeparator()
        self.menuSetBoardCoords.addAction(self.menuabc123.menuAction())
        self.menuSetBoardCoords.addSeparator()
        self.menuSetBoardCoords.addAction(self.actionab)
        self.menuSetBoardCoords.addAction(self.actionab_2)
        self.menubar.addAction(self.menuSetBoardCoords.menuAction())

        self.retranslateUi(MainWindow)
        self.pushButton_2.clicked.connect(self.pushButton_2.hide) # type: ignore
        self.pushButton.clicked.connect(self.pushButton.hide) # type: ignore
        self.pushButton.clicked.connect(self.pushButton_2.show) # type: ignore
        self.pushButton_2.clicked.connect(self.pushButton.show) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_2.setText(_translate("MainWindow", "PushButton"))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "Mew Mew Mews\n"
""))
        self.radioButton.setText(_translate("MainWindow", "White to move"))
        self.radioButton_2.setText(_translate("MainWindow", "Black to move"))
        self.pushButton_3.setText(_translate("MainWindow", "Submit haha"))
        self.subwindow_0.setText(_translate("MainWindow", "Subwindow"))
        self.menuSetBoardCoords.setTitle(_translate("MainWindow", "SetBoardCoords"))
        self.menuabc123.setTitle(_translate("MainWindow", "abc123"))
        self.actionab.setText(_translate("MainWindow", "ab"))
        self.actionab_2.setText(_translate("MainWindow", "ab"))
        self.actionhello.setText(_translate("MainWindow", "hello"))
